name: Alpine Parrot
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#5e697f'
    - '#9f9ea4'
    - '#fffcff'
    - '#ffac0e'
  brandStrength: 0.5
  lightness: 0.8896983635536424
  saturation: 0.8360832804405245
  rhythmicContrast: 0.048212524217797426
purpose:
  - name: null
    item: null
    url: null
